---
title: "R Notebook"
output: html_document
---


```{r}
library(dplyr)
library(meta)
data <- data.frame(
  Study = c("Barnard, 2005", "Barnard, 2006", "Kahleova, 2020", "Mishra, 2013", "Wright, 2017", "Burke, 2006", "Kahleova, 2017", "Karlsson, 1994"),
  Vegetarian = c(29, 49, 122, 142, 32, 84, 37, 28),
  Omnivore = c(30, 50, 122, 149, 32, 98, 37, 32),
  Mean_veg = c(-5.8, -5.9, -6.4, -2.9, -8.1, -7.5, -6.2, -3.9),
  Mean_omn = c(-3.8, -4.3, -0.5, 0, -1.6, -6.97, -3.2, 1.8),
  SD_veg = c(9.5, 16, 9.9, 1.3, 4.4, 10.6, 2.79, 8.5),
  SD_omn = c(8.6, 14.8, 10.6, 1.3, 5.3, 10.8, 2.17, 8)
)


```
```{r}

```
position the caret at any line or the code chunk, then click "+".

The code chunk appears:
```{r}

meta_med <- metacont(n.e = Vegetarian,
                     mean.e = Mean_veg,
                     sd.e = SD_veg,
                     n.c = Omnivore,
                     mean.c = Mean_omn,
                     sd.c = SD_omn,
                     studlab = Study,
                     data = data,
                     comb.fixed = FALSE,
                     comb.random = TRUE,
                     method.tau = "REML",
                     hakn = TRUE,
                     title = "Veg vs omnivore",
                     prediction = TRUE)
png(file = "forestplot_med.png", width = 2600, height = 1200, res=300, bg="#F1EFE6")
forest(meta_med,
       sortvar = TE,
       prediction = TRUE,
       print.tau2 = FALSE,
       leftcols = c("studlab", "mean.e", "mean.c"),
       leftlabs = c("Publication", "kg lost VD", "kg lost OD"),
       label.left = "Favours Vegetarian",
       label.right = "Favours Omnivore",
       just = "center")
dev.off()
```

Type any R code in the chunk, for example:
```{r}
mycars <- within(mtcars, { cyl <- ordered(cyl) })
mycars
```

Now, click the **Run** button on the chunk toolbar to [execute](https://www.jetbrains.com/help/pycharm/r-markdown.html#run-r-code) the chunk code. The result should be placed under the chunk.
Click the **Knit and Open Document** to build and preview an output.